#!/bin/bash

dir=$1
if [ -z "$dir" ] || [ ! -d "$dir" ]; then
	echo "Hint: $0 <path-java_dir>"
	exit 1
fi

find "$dir" -name "*.java" | while read -r file; do
	cnt=$(grep "^import " "$file" | sort -u | wc -l)
	echo "Cantidad de imports de $(basename "$file") es: "$cnt""
done
