#!/bin/bash

dir=$1
if [ -z "$dir" ] || [ ! -d "$dir" ]; then
	echo "Hint: $0 <path-java_dir>"
	exit 1
fi
cnt=$(grep -h "^import " "$dir"/*.java 2>/dev/null | sort -u | wc -l)
echo "Cantidad de imports es: "$cnt""

echo "Detalle de las importaciones encontradas:"
grep -h "^import " "$dir"/*.java 2>/dev/null | sort -u
